"""empty message

Revision ID: 2dbf9a3ee4d7
Revises: 5c05c4b77cdf
Create Date: 2022-06-10 09:55:08.760999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbf9a3ee4d7'
down_revision = '5c05c4b77cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'quantity')
    # ### end Alembic commands ###
